import "./globals.css";

import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import { twMerge } from "tailwind-merge";

import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";

const ubuntuFont = Ubuntu({subsets: ["latin"], weight: ["300", "400", "500", "700"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={twMerge(ubuntuFont.className, "text-sm bg-neutral-100")}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
