import "./globals.css";

import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import { twMerge } from "tailwind-merge";

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

import NextTopLoader from "nextjs-toploader";

const ubuntuFont = Ubuntu({subsets: ["latin"], weight: ["300", "400", "500", "700"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="icon" href="/images/favicon.ico" sizes="any" />
      </head>
      <body className={twMerge(ubuntuFont.className, "text-sm bg-neutral-100")}>
        <NextTopLoader 
          color="red"
        />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
