version: "3.8"

services:   
    technews:
        build:
          context: .
          network: host
        ports:
            - 3001:3001
        env_file:
            - .env
        network_mode: host
    
